services:
  composer-install:
    image: php:8.3.2-cli-bookworm
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - php
      - /app/composer.phar
      - install
      - --no-interaction
      - --ansi
      - --no-plugins
      - --no-scripts
  unit-tests:
    image: php:8.3.2-cli-bookworm
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      composer-install:
        condition: service_completed_successfully
    command:
      - ./vendor/bin/phpunit
      - -c
      - ./tests/phpunit.xml
